import { StyleSheet } from 'react-native';

import { C } from '@/constants/theme';

export const styles = StyleSheet.create({
  card: { backgroundColor: C.card, borderWidth: 1, borderColor: C.line, borderRadius: 20, padding: 16, gap: 14 },
  weekHeader: { marginBottom: 4 },
  wd: { flex: 1, textAlign: 'center' },
  cell: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  center: { alignItems: 'center', justifyContent: 'center' },
  ring: { borderWidth: 2, borderColor: 'transparent' },
  ringSelected: { borderColor: C.ink },
  ringSelectedToday: { borderColor: C.outBar },
  dayToday: { backgroundColor: C.ink },
  dayHoliday: { backgroundColor: C.holidaySoft },
  outOfMonth: { opacity: 0.3 },
  dotRing: { backgroundColor: 'transparent', borderWidth: 1.4 },
  swatch: { width: 12, height: 12, borderRadius: 6 },
  swatchToday: { backgroundColor: C.ink },
  swatchHoliday: { backgroundColor: C.holidaySoft, borderWidth: 1, borderColor: C.holiday },
  legend: { flexWrap: 'wrap', rowGap: 6 },
  pickerTitle: { letterSpacing: -0.3 },
  todayBtn: {
    height: 44,
    paddingHorizontal: 14,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.card,
    justifyContent: 'center',
  },
  pickerGrid: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 20,
    paddingHorizontal: 4,
    paddingVertical: 10,
  },
  yearGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  miniCard: {
    width: '31.4%',
    flexGrow: 1,
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 16,
    padding: 8,
    gap: 6,
  },
  miniCardCurrent: { borderColor: C.ink, borderWidth: 1.5 },
  miniBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    backgroundColor: C.holidaySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniCell: { flex: 1, alignItems: 'center', height: 17 },
  miniNum: { width: 13, height: 13, borderRadius: 7 },
  miniDot: { width: 3, height: 3, borderRadius: 2, marginTop: 1 },
  nextHol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: C.divider,
    paddingTop: 12,
  },
  nextHolDate: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: C.holidaySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
