import { StyleSheet } from 'react-native';

import { C, F } from '@/constants/theme';

export const styles = StyleSheet.create({
  tabular: { fontVariant: ['tabular-nums'] },
  screen: { flex: 1, backgroundColor: C.bg },
  screenContent: { paddingHorizontal: 20 },
  row: { flexDirection: 'row', alignItems: 'center' },
  pressed: { opacity: 0.6 },
  card: { backgroundColor: C.card, borderWidth: 1, borderColor: C.line, borderRadius: 20 },

  header: { justifyContent: 'space-between', alignItems: 'flex-end' },
  headerTitle: { letterSpacing: -0.5 },
  round: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionTitle: { justifyContent: 'space-between', alignItems: 'baseline' },

  segWrap: { backgroundColor: C.segBg, borderRadius: 16, padding: 4, flexDirection: 'row', gap: 4 },
  segBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  segOn: {
    backgroundColor: C.card,
    shadowColor: C.ink,
    shadowOpacity: 0.12,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },

  chip: { height: 44, paddingHorizontal: 16, borderRadius: 22, borderWidth: 1, justifyContent: 'center' },
  progressTrack: { borderRadius: 99, overflow: 'hidden' },
  progressFill: { borderRadius: 99 },

  track: { width: 50, height: 30, borderRadius: 15, padding: 3, flexDirection: 'row', alignItems: 'center' },
  trackOn: { justifyContent: 'flex-end' },
  trackOff: { justifyContent: 'flex-start', backgroundColor: C.switchOff },
  trackDisabled: { opacity: 0.4 },
  knob: { width: 24, height: 24, borderRadius: 12, backgroundColor: C.white },

  tip: {
    position: 'absolute',
    top: 26,
    left: -12,
    width: 260,
    backgroundColor: C.ink,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    zIndex: 10,
    elevation: 6,
    shadowColor: C.shadow,
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  tipArrow: {
    position: 'absolute',
    top: -5,
    left: 15,
    width: 10,
    height: 10,
    backgroundColor: C.ink,
    transform: [{ rotate: '45deg' }],
  },
  tipText: { lineHeight: 18 },

  listRow: { paddingVertical: 12, minHeight: 56 },
  listRowRaised: { zIndex: 1 },
  divider: { borderTopWidth: 1, borderTopColor: C.divider },

  stepper: { backgroundColor: C.chip, borderRadius: 14, padding: 4 },
  stepBtn: {
    width: 40,
    height: 40,
    borderRadius: 11,
    backgroundColor: C.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepInput: {
    height: 40,
    borderRadius: 11,
    backgroundColor: C.card,
    textAlign: 'center',
    fontFamily: F[800],
    fontSize: 15,
    color: C.ink,
    padding: 0,
  },
  stepValue: { textAlign: 'center' },

  radio: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  radioOff: { borderColor: C.ring },
  radioDot: { width: 10, height: 10, borderRadius: 5 },

  primary: {
    height: 56,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  field: {
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.card,
    fontFamily: F[500],
    fontSize: 14.5,
    color: C.ink,
    paddingHorizontal: 14,
  },

  toast: {
    backgroundColor: C.card,
    borderWidth: 1.5,
    borderRadius: 18,
    paddingVertical: 12,
    paddingLeft: 12,
    paddingRight: 4,
  },
  toastIcon: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  toastClose: { padding: 10 },
  empty: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: C.dashed,
    borderRadius: 20,
    paddingVertical: 22,
    paddingHorizontal: 16,
    alignItems: 'center',
    gap: 4,
  },

  backdrop: { flex: 1, backgroundColor: C.backdrop },
  sheet: {
    maxHeight: '85%',
    backgroundColor: C.bg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 10,
    paddingHorizontal: 20,
  },
  sheetContent: { gap: 14 },
  sheetHeader: { justifyContent: 'space-between', alignItems: 'flex-start' },
  handle: { alignSelf: 'center', width: 40, height: 5, borderRadius: 3, backgroundColor: C.handle, marginBottom: 10 },

  movRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12 },
  movAmount: { alignItems: 'flex-end', gap: 3 },
  avatar: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  avatarIn: { backgroundColor: C.inSoft },
  avatarOut: { backgroundColor: C.outSoft },
  check: { width: 42, height: 42, borderRadius: 21, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  checkOn: { borderColor: C.ink, backgroundColor: C.ink },
  checkOff: { borderColor: C.ring, backgroundColor: C.card },
  badge: { backgroundColor: C.chip, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 2, overflow: 'hidden' },
});
