import { StyleSheet } from 'react-native';

import { C } from '@/constants/theme';

export const styles = StyleSheet.create({
  hero: { backgroundColor: C.inDark, borderRadius: 24, padding: 22, gap: 18 },
  heroAmount: { letterSpacing: -1 },
  heroTile: { flex: 1, backgroundColor: C.in, borderRadius: 16, padding: 14, gap: 4 },
  /** Barra del ahorro total: libre + un tramo por meta. */
  split: { flexDirection: 'row', height: 10, borderRadius: 99, overflow: 'hidden', gap: 2, backgroundColor: C.in },
  splitPart: { height: 10 },
  legend: { flexDirection: 'row', flexWrap: 'wrap', columnGap: 14, rowGap: 6 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  action: { flex: 1, alignSelf: 'stretch', backgroundColor: C.card, borderWidth: 1, borderColor: C.line, borderRadius: 18, padding: 14, gap: 4 },
  actionIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: C.inSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  goal: { backgroundColor: C.card, borderWidth: 1, borderColor: C.line, borderRadius: 18, padding: 16, gap: 14 },
  contribute: { height: 40, paddingHorizontal: 16, borderRadius: 12, backgroundColor: C.in, justifyContent: 'center' },
  /** Filtros del historial y metas de origen de un aporte. */
  filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filter: { height: 36, paddingHorizontal: 14, maxWidth: '100%' },
  emptyHistory: { paddingVertical: 16, textAlign: 'center' },
  histRow: { paddingVertical: 12 },
  histIconAdd: { backgroundColor: C.in },
  histIconUpdate: { backgroundColor: C.inSoft },
  histIconWithdraw: { backgroundColor: C.outSoft },
  ref: { backgroundColor: C.card, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 14, gap: 12 },
  quick: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  /** Nueva meta: botón "Aportar ahora" y acciones del aporte inicial. */
  startBtn: {
    height: 50,
    borderRadius: 16,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: C.inTrack2,
    backgroundColor: C.inSoft,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  startEdit: {
    height: 36,
    minWidth: 36,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: C.chip,
    alignItems: 'center',
    justifyContent: 'center',
  },
  preview: { borderRadius: 16, paddingVertical: 14, paddingHorizontal: 16, gap: 12 },
  previewNeutral: { backgroundColor: C.chip },
  previewPositive: { backgroundColor: C.inSoft },
  previewNegative: { backgroundColor: C.outSoft },
});
