import { StyleSheet } from 'react-native';

import { C } from '@/constants/theme';

export const styles = StyleSheet.create({
  content: { paddingHorizontal: 16, gap: 14 },
  header: { gap: 12 },
  title: { letterSpacing: -0.5 },
  modeToggle: { flexShrink: 1 },
  chevron: { marginTop: 6 },
  chevronOpen: { transform: [{ rotate: '180deg' }] },
  fixedHead: { backgroundColor: C.card, borderWidth: 1, borderColor: C.line, borderRadius: 18, padding: 12 },
  fixedAvatar: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  fixedAvatarIn: { backgroundColor: C.inSoft },
  fixedAvatarOut: { backgroundColor: C.outSoft },
  listCard: { paddingHorizontal: 14, paddingVertical: 4 },
  emptyPayments: { textAlign: 'center', paddingVertical: 14 },
  payDate: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'transparent',
    backgroundColor: C.chip,
    alignItems: 'center',
    justifyContent: 'center',
  },
  payDateSelected: { borderColor: C.ink },
  payDatePaidIn: { backgroundColor: C.inSoft },
  payDatePaidOut: { backgroundColor: C.outSoft },
  todayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    height: 40,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.line,
  },
  todayDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.ink },
  gridCard: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 24,
    paddingHorizontal: 6,
    paddingVertical: 12,
  },
  stat: { height: 30, paddingHorizontal: 12, borderRadius: 15, justifyContent: 'center' },
  detail: { backgroundColor: C.card, borderWidth: 1, borderColor: C.line, borderRadius: 22, padding: 16, gap: 12 },
  bigDay: { width: 54, height: 54, borderRadius: 18, backgroundColor: C.chip, alignItems: 'center', justifyContent: 'center' },
  bigDayToday: { backgroundColor: C.ink },
  bigDayHoliday: { backgroundColor: C.holidaySoft },
  weekday: { textTransform: 'capitalize' },
  holBanner: { backgroundColor: C.holidaySoft, borderRadius: 14, paddingVertical: 10, paddingHorizontal: 12 },
  holBannerDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: C.holiday },
  emptyDay: { textAlign: 'center', paddingVertical: 10 },
  totals: { paddingTop: 12, justifyContent: 'flex-end' },
  addBtn: {
    height: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: C.ring,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  holRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10 },
  holDate: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: C.holidaySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  years: { gap: 8, paddingHorizontal: 2 },
  yearChip: {
    height: 40,
    minWidth: 62,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  yearChipOn: { backgroundColor: C.ink, borderColor: C.ink },
});
