import { StyleSheet } from 'react-native';

import { C, F } from '@/constants/theme';

export const styles = StyleSheet.create({
  search: {
    height: 48,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: C.in,
    backgroundColor: C.card,
    paddingLeft: 14,
    paddingRight: 4,
  },
  searchInput: { flex: 1, fontFamily: F[600], fontSize: 15, color: C.ink, padding: 0 },
  searchClear: { padding: 12 },
  hero: { backgroundColor: C.hero, borderRadius: 24, padding: 20, gap: 14 },
  heroAmount: { letterSpacing: -0.5 },
  list: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 4,
  },
  gastoRow: { paddingVertical: 10 },
  check: { width: 44, height: 44, borderRadius: 22, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  checkOn: { borderColor: C.ink, backgroundColor: C.ink },
  checkOff: { borderColor: C.ring, backgroundColor: C.card },
  gastoBody: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 44 },
  incHero: { backgroundColor: C.inSoft, borderRadius: 20, padding: 16, gap: 10 },
  incCard: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 12,
  },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  incAmount: { alignItems: 'flex-end', gap: 2, minHeight: 44, justifyContent: 'center' },
  periodBtn: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: C.bg,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  receive: {
    height: 46,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: C.in,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  receiveOn: { backgroundColor: C.in },
  receiveOff: { backgroundColor: C.card },
});
