import { StyleSheet } from 'react-native';

import { C } from '@/constants/theme';

export const styles = StyleSheet.create({
  pendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 20,
    height: 20,
    paddingHorizontal: 5,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: C.bg,
    backgroundColor: C.out,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chartCard: { padding: 18, gap: 14 },
  bars: { alignItems: 'flex-end' },
  barColumn: { flex: 1, alignItems: 'center', gap: 8 },
  barPair: { alignItems: 'flex-end' },
  legend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 8,
    columnGap: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: C.dividerSoft,
  },
  legendItem: { width: '48%' },
  swatch: { width: 10, height: 10, borderRadius: 3 },
  swatchDashed: { borderWidth: 1.5, borderStyle: 'dashed', borderColor: C.muted },
  bar: { width: 12, gap: 2 },
  baseBar: { borderRadius: 3 },
  baseBarTop: { borderTopLeftRadius: 6, borderTopRightRadius: 6 },
  pendBar: { borderWidth: 1.5, borderStyle: 'dashed', borderTopLeftRadius: 6, borderTopRightRadius: 6, borderRadius: 3 },
  topBar: {
    backgroundColor: C.extra,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderBottomLeftRadius: 3,
    borderBottomRightRadius: 3,
  },
  monthCard: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 10,
  },
  current: { backgroundColor: C.ink, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3, overflow: 'hidden' },
  extraTag: { backgroundColor: C.extraSoft, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, overflow: 'hidden' },
  pendTag: {
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: C.faint,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  allDone: { paddingVertical: 22, paddingHorizontal: 16, alignItems: 'center', gap: 6 },
  pendCard: {
    backgroundColor: C.card,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: C.dashedDark,
    borderRadius: 18,
    padding: 14,
    gap: 12,
  },
  pendIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  pendIconIn: { backgroundColor: C.inIconBg },
  pendIconOut: { backgroundColor: C.outIconBg },
  pendAction: {
    flex: 1,
    height: 44,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  pendDelete: { borderWidth: 1.5, borderColor: C.line, backgroundColor: C.card },
  pendConfirm: { backgroundColor: C.extra },
  resolvedRow: { minHeight: 44 },
  resolvedName: { flex: 1 },
  resolvedSkipped: { textDecorationLine: 'line-through' },
  tag: { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, overflow: 'hidden' },
  tagExtra: { backgroundColor: C.extraSoft },
  tagSkipped: { backgroundColor: C.chipMuted },
  undo: { padding: 10 },
});
